# Generated by Django 3.2.5 on 2021-08-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentImages',
            new_name='StudentImage',
        ),
    ]
