# Generated by Django 3.2.5 on 2021-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_studentimages_studentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
