# Generated by Django 3.2.5 on 2021-08-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(upload_to='student/'),
        ),
        migrations.AlterField(
            model_name='studentimage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentimage_set', to='attendance.student'),
        ),
    ]
